import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      
      <body className="min-h-full flex flex-col">
        {children}
        <div className="navbar">
          <a href={`/`}>홈</a>
          <a href={`/timetable`}>1주일 시간표</a>
          <a href={`/notice`}>공지사항</a>
          <a href={`/eat`}>1주일 급식</a>
        </div>
      </body>
    </html>
  );
}
